/*
===========================================================================
Copyright (C) 2006 Dmn_clown (aka: Bob Isaac (rjisaac@gmail.com))

This file is part of Open Arena and is based upon Mr. Elusive's fuzzy logic
system found in Quake 3 Arena.

Open Arena is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Open Arena is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Foobar; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/

#include "chars.h"


skill 1
{
	CHARACTERISTIC_NAME							"Gargoyle"
	CHARACTERISTIC_GENDER						"Male"
	CHARACTERISTIC_ATTACK_SKILL					0
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gargoyle_w.c"
	CHARACTERISTIC_AIM_SKILL					0.0
	CHARACTERISTIC_AIM_ACCURACY					0.0
	CHARACTERISTIC_VIEW_FACTOR					0.0
	CHARACTERISTIC_VIEW_MAXCHANGE		                        2.0		
	CHARACTERISTIC_REACTIONTIME					5.0

	CHARACTERISTIC_CHAT_FILE					"bots/gargoyle_t.c"
	CHARACTERISTIC_CHAT_NAME					"gargoyle"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.900
	CHARACTERISTIC_CHAT_MISC					0.750
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.900
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.000
	CHARACTERISTIC_CHAT_KILL					1.000
	CHARACTERISTIC_CHAT_DEATH					0.900
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.000
	CHARACTERISTIC_CHAT_HITTALKING				0.900
	CHARACTERISTIC_CHAT_HITNODEATH				0.800
	CHARACTERISTIC_CHAT_HITNOKILL				1.000
	CHARACTERISTIC_CHAT_RANDOM					0.900
	CHARACTERISTIC_CHAT_REPLY					1.000

	CHARACTERISTIC_CROUCHER						0.200
	CHARACTERISTIC_JUMPER						0.100
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				        0.100
	CHARACTERISTIC_GRAPPLE_USER					0.10
	CHARACTERISTIC_ITEMWEIGHTS					"bots/gargoyle_i.c"
	CHARACTERISTIC_AGGRESSION					0.250
	CHARACTERISTIC_SELFPRESERVATION				        0.100
	CHARACTERISTIC_VENGEFULNESS					0.100
	CHARACTERISTIC_CAMPER						0.000
	CHARACTERISTIC_EASY_FRAGGER					0.000
	CHARACTERISTIC_ALERTNESS					0.100

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	 	        0.0
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.0
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	        0.0
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	        0.0
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		        0.0
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		        0.0
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.0
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		        0.0
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	        0.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.0
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.0

	CHARACTERISTIC_FIRETHROTTLE					0.20
}

skill 2
{
	CHARACTERISTIC_NAME							"Gargoyle"
	CHARACTERISTIC_GENDER						"Male"
	CHARACTERISTIC_ATTACK_SKILL					0.25
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gargoyle_w.c"
	CHARACTERISTIC_AIM_SKILL					0.25
	CHARACTERISTIC_AIM_ACCURACY					0.25
	CHARACTERISTIC_VIEW_FACTOR					0.3
	CHARACTERISTIC_VIEW_MAXCHANGE		                        90		
	CHARACTERISTIC_REACTIONTIME					4.0

	CHARACTERISTIC_CHAT_FILE					"bots/gargoyle_t.c"
	CHARACTERISTIC_CHAT_NAME					"gargoyle"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.900
	CHARACTERISTIC_CHAT_MISC					0.750
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.900
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.000
	CHARACTERISTIC_CHAT_KILL					1.000
	CHARACTERISTIC_CHAT_DEATH					0.900
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.000
	CHARACTERISTIC_CHAT_HITTALKING				0.900
	CHARACTERISTIC_CHAT_HITNODEATH				0.800
	CHARACTERISTIC_CHAT_HITNOKILL				1.000
	CHARACTERISTIC_CHAT_RANDOM					0.900
	CHARACTERISTIC_CHAT_REPLY					1.000

	CHARACTERISTIC_CROUCHER						0.150
	CHARACTERISTIC_JUMPER						0.300
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				        0.300
	CHARACTERISTIC_GRAPPLE_USER					0.30
	CHARACTERISTIC_ITEMWEIGHTS					"bots/gargoyle_i.c"
	CHARACTERISTIC_AGGRESSION					0.375
	CHARACTERISTIC_SELFPRESERVATION				        0.300
	CHARACTERISTIC_VENGEFULNESS					0.300
	CHARACTERISTIC_CAMPER						0.250
	CHARACTERISTIC_EASY_FRAGGER					0.250
	CHARACTERISTIC_ALERTNESS					0.300

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN	 	        0.15
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.22
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	        0.22
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	        0.17
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		        0.17
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		        0.22
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.22
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.22
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		        0.2
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	        0.2
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.2
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.2

	CHARACTERISTIC_FIRETHROTTLE					0.225
}

skill 3
{
	CHARACTERISTIC_NAME							"Gargoyle"
	CHARACTERISTIC_GENDER						"female"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gargoyle_w.c"
	CHARACTERISTIC_AIM_SKILL					0.5
	CHARACTERISTIC_AIM_ACCURACY					0.5
	CHARACTERISTIC_VIEW_FACTOR					0.6
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					3.0

	CHARACTERISTIC_CHAT_FILE					"bots/gargolyle_t.c"
	CHARACTERISTIC_CHAT_NAME					"Gargoyle"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					1.0
	CHARACTERISTIC_CHAT_MISC					1.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL			1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.0
	CHARACTERISTIC_CHAT_KILL					1.0
	CHARACTERISTIC_CHAT_DEATH					1.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.0
	CHARACTERISTIC_CHAT_HITTALKING				1.0
	CHARACTERISTIC_CHAT_HITNODEATH				1.0
	CHARACTERISTIC_CHAT_HITNOKILL				1.0
	CHARACTERISTIC_CHAT_RANDOM					1.0
	CHARACTERISTIC_CHAT_REPLY					1.0

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WALKER						0.0
	CHARACTERISTIC_WEAPONJUMPING				0.5
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gargoyle_i.c"
	CHARACTERISTIC_AGGRESSION					0.5
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5
	CHARACTERISTIC_CAMPER						0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.5

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.3
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.45
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.45
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.35
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.35
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.45
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.45
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.45
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.4
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.4
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.4
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.4

	CHARACTERISTIC_FIRETHROTTLE					0.25
}

skill 4
{
	CHARACTERISTIC_NAME							"Gargoyle"
	CHARACTERISTIC_GENDER						"Male"
	CHARACTERISTIC_ATTACK_SKILL					1.000
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gargoyle_w.c"
	CHARACTERISTIC_AIM_SKILL					1.000
	CHARACTERISTIC_AIM_ACCURACY					1.000
	CHARACTERISTIC_VIEW_FACTOR					0.900
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_REACTIONTIME					1.25

	CHARACTERISTIC_CHAT_FILE					"bots/gargoyle_t.c"
	CHARACTERISTIC_CHAT_NAME					"gargoyle"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.900
	CHARACTERISTIC_CHAT_MISC					0.750
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.900
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.000
	CHARACTERISTIC_CHAT_KILL					1.000
	CHARACTERISTIC_CHAT_DEATH					0.900
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.000
	CHARACTERISTIC_CHAT_HITTALKING				0.900
	CHARACTERISTIC_CHAT_HITNODEATH				0.800
	CHARACTERISTIC_CHAT_HITNOKILL				1.000
	CHARACTERISTIC_CHAT_RANDOM					0.900
	CHARACTERISTIC_CHAT_REPLY					1.000

	CHARACTERISTIC_CROUCHER						0.100
	CHARACTERISTIC_JUMPER						1.000
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				1.000
	CHARACTERISTIC_GRAPPLE_USER					1.000

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gargoyle_i.c"
	CHARACTERISTIC_AGGRESSION					1.000
	CHARACTERISTIC_SELFPRESERVATION				1.000
	CHARACTERISTIC_VENGEFULNESS					1.000
	CHARACTERISTIC_CAMPER						0.500

	CHARACTERISTIC_EASY_FRAGGER					1.000
	CHARACTERISTIC_ALERTNESS					1.000

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.900
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			0.900
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.900
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.900
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.900
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		0.900
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			0.900
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			0.900
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		0.900
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	0.900
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			0.900
	CHARACTERISTIC_AIM_SKILL_BFG10K				0.900

	CHARACTERISTIC_FIRETHROTTLE					0.900
}

skill 5
{
	CHARACTERISTIC_NAME							"Gargoyle"
	CHARACTERISTIC_GENDER						"Male"
	CHARACTERISTIC_ATTACK_SKILL					1.000
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/gargoyle_w.c"
	CHARACTERISTIC_AIM_SKILL					1.000
	CHARACTERISTIC_AIM_ACCURACY					1.000
	CHARACTERISTIC_VIEW_FACTOR					1.000
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.00

	CHARACTERISTIC_CHAT_FILE					"bots/gargoyle_t.c"
	CHARACTERISTIC_CHAT_NAME					"gargoyle"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.900
	CHARACTERISTIC_CHAT_MISC					0.750
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.900
	CHARACTERISTIC_CHAT_ENTEREXITGAME			1.000
	CHARACTERISTIC_CHAT_KILL					1.000
	CHARACTERISTIC_CHAT_DEATH					0.900
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			1.000
	CHARACTERISTIC_CHAT_HITTALKING				0.900
	CHARACTERISTIC_CHAT_HITNODEATH				0.800
	CHARACTERISTIC_CHAT_HITNOKILL				1.000
	CHARACTERISTIC_CHAT_RANDOM					0.900
	CHARACTERISTIC_CHAT_REPLY					1.000

	CHARACTERISTIC_CROUCHER						0.000
	CHARACTERISTIC_JUMPER						1.000
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				1.000
	CHARACTERISTIC_GRAPPLE_USER					1.000

	CHARACTERISTIC_ITEMWEIGHTS					"bots/gargoyle_i.c"
	CHARACTERISTIC_AGGRESSION					1.000
	CHARACTERISTIC_SELFPRESERVATION				1.000
	CHARACTERISTIC_VENGEFULNESS					1.000
	CHARACTERISTIC_CAMPER						0.000

	CHARACTERISTIC_EASY_FRAGGER					1.000
	CHARACTERISTIC_ALERTNESS					1.000

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.700
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			1.000
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	1.000
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	1.000
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		1.000
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		1.000
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			1.000
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			1.000
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.000
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.000
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			1.000
	CHARACTERISTIC_AIM_SKILL_BFG10K				1.000

	CHARACTERISTIC_FIRETHROTTLE					1.000
}

